# PROBLEM 2 - Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

input = 4000000
sum = 0

a = 1
b = 1
temp = 0

while a <= input
	sum += b if(b%2 == 0)
	temp = b
	b += a
	a = temp	
end

puts sum

# OUTPUT
# 4613732
# real	0m0.042s
# user	0m0.032s
# sys	0m0.007s