# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

i = 0
j = 1
sum=0
while((i<=4000000) && (j<=4000000))
    i = i + j
    j = i + j
    if(i%2 == 0)
        sum += i
    elsif(j%2 == 0)
        sum += j
    end
end

puts sum