=begin 

  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

=end 


# Generate the fibonacci series till a number less than 4 million. If there is an even number, add it to the sum.
array = []
array[0]=1
array[1]=1
k=2
sum = 0

while array[k-1] <4000000

  array[k] = array[k-1]+array[k-2]
  
  sum = sum + array[k] if array[k]%2==0
  
  k += 1
end

puts sum

